# Numerical Python (NumPy)

NumPy is fundamental package for scientific computing with Python which adding support for large, multi-dimensional arrays and matrices, along with an extensive library of [high-level mathematical functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html) to operate on these arrays.

In Python to import modules or libraries we do is as:
**import module_name**

if we wish we can give an alias name to the module:
** import module_name as alias**

In [1]:
# Importing NumPy
import numpy as np

### Creating NumPy arrays

In [5]:
# Creating a list
list_example = [1, 2, 3]

# Converting a list in a NumPy array
x = np.array(list_example)

In [6]:
x

array([1, 2, 3])

In [7]:
type(x)

numpy.ndarray

In [8]:
# Also it can be created as:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Pass in a list of lists to create a multidimensional array.

In [9]:
matrix = np.array([[7, 8, 9], [10, 11, 12]])
matrix

array([[ 7,  8,  9],
       [10, 11, 12]])

We use the **shape method** to find the dimensions of the array: rows X columns.

In [12]:
matrix.shape

(2, 3)

We can use also *arange(start, end, increase_by)* method 

In [15]:
# start at 0 increaisng up by 2, stop before 30
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [16]:
# Checking the number of elements in the array
len(n)

15

`reshape` returns an array with the same data with a new shape. We can reshape it as 3 x 5, 5 x 3 since we have 15 items in the original array.

In [17]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [18]:
n = n.reshape(5, 3) # reshape array to be 3x5
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

*linspace* returns evenly spaced numbers over a specified interval.

In [27]:
# Return 9 evenly spaced values from 0 to 4
l = np.linspace(0, 4, 9)
l

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [28]:
# We can reshape the array
l.reshape(3, 3)

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [29]:
l

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

*resize* changes the shape and size of array in-place.

In [30]:
l.resize(3, 3)

In [32]:
# The change has been permanetly done in the array l
l

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

*ones* returns a new array of given shape filled with ones.

In [33]:
np.ones((4, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

*zeros* returns a new array of given shape filled with zeros.

In [34]:
np.zeros((4, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

*eye* returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [35]:
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

Repeat elements of an array using repeat.

In [36]:
np.repeat([2, 5, 6], 2)

array([2, 2, 5, 5, 6, 6])

Create an array using repeating list (or see *np.tile*)

In [37]:
np.array([2, 5, 6] * 2)

array([2, 5, 6, 2, 5, 6])

In [38]:
np.tile([2, 5, 6], 2)

array([2, 5, 6, 2, 5, 6])

### Combining Arrays

In [39]:
# By defualt the elements of an array are float, so we can change the type 
f = np.ones([2, 3], int)

In [42]:
f

array([[1, 1, 1],
       [1, 1, 1]])

To stack a sequence vertically (row wise) we use *vstack*

In [46]:
# We can passs a tuple with the arrays that will be stacked
np.vstack((f, 2 * f))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Use *hstack* to stack arrays in sequence horizontally (column wise).

In [49]:
np.hstack((f, 2 * f))

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [47]:
# We can do the same with *concatenate* and axis=0 refers to rows and axis=1 to columns  
np.concatenate((f, 2 * f), axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [48]:
np.concatenate((f, 2 * f), axis=1)

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### Operations

To perform element wise addition, subtraction, multiplication, division and power +, -, *, /

In [50]:
x

array([1, 2, 3])

In [51]:
y

array([4, 5, 6])

In [56]:
print x + y # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print x - y # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [57]:
print x * y # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print x / y # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0 0 0]


In [55]:
print x**2 # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [58]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [60]:
g = np.array([y, y**2])
g

array([[ 4,  5,  6],
       [16, 25, 36]])

In [61]:
# number of rows
len(g)

2

Now we will look at transposing arrays. Transposing permutes the dimensions of the array.

<img src="Transpose.jpg" alt="Drawing" style="width: 300px;"/>

In [63]:
h = np.array([y, y**2])
h

array([[ 4,  5,  6],
       [16, 25, 36]])

In [65]:
h.shape

(2, 3)

In [66]:
h.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [68]:
h.T.shape

(3, 2)

In [71]:
# Use .dtype to see the data type of the elements in the array.
h.dtype

dtype('int64')

In [74]:
# Use .astype changes the data type of the elements in the array.
h = h.astype('f')
h.dtype

dtype('float32')

In [75]:
h

array([[  4.,   5.,   6.],
       [ 16.,  25.,  36.]], dtype=float32)

### Math Functions

Numpy has many buil-in math functions that can be performed on arrays. Yu can find and extensive list [here](https://docs.scipy.org/doc/numpy/reference/routines.math.html). Here we show some of them.

In [76]:
p = np.array([3, 4, 5, 6, 7, 7, 3, 4])

In [77]:
p.min()

3

In [78]:
p.max()

7

In [79]:
p.sum()

39

In [80]:
p.mean()

4.875

In [82]:
p.std()

1.5360257159305635

`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [90]:
# It is looking from left to right
p.argmax()

4

In [89]:
p.argmin()

0

### Indexing / Slicing

In [95]:
# Element wise operation
t = np.arange(12)**2 
t

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

We perform slices as we already learned using brackets. Remeber that indexing starts with zero. To slice an array we use as before [start:stop].

In [101]:
t[0], t[4], t[-1]

(0, 16, 121)

In [102]:
t[3:6]

array([ 9, 16, 25])

In [106]:
# Use negatives to count from the back.
t[-4:]

array([ 64,  81, 100, 121])

We can indiacte step-size: array[start:stop:stepsize]

In [108]:
# Here we are starting 5th element from the end, and counting backwards by 
# 2 until the beginning of the array is reached.
t[-5::-2]

array([49, 25,  9,  1])

In [110]:
# Here we are starting 5th element from the end, and counting backwards by 
# 2 until the array is reached the 2nd possition.
t[-5:2:-2]

array([49, 25,  9])

In [111]:
# In this we are starting from the zero element and counting fowards by 3 until the end of the array. 
t[::3]

array([ 0,  9, 36, 81])

Multidimensional array.

In [112]:
w = np.arange(36)
w.resize((6, 6))
w

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: `array[row, column]`

In [113]:
w[2, 2]

14

To select a range of rows or columns.

In [115]:
w[3, :]

array([18, 19, 20, 21, 22, 23])

In [120]:
w[:, 3:6]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [122]:
w[2:4, 3:6]

array([[15, 16, 17],
       [21, 22, 23]])

Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [123]:
w[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

This is a slice of the last row, and only every other element.

In [124]:
w[-1, ::2]

array([30, 32, 34])

We can also perform conditional indexing. 

In [126]:
w[w > 30]

array([31, 32, 33, 34, 35])

Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [127]:
w[w > 30] = 30

In [128]:
w

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### Copying Data

You should be careful with copying and modifying arrays in NumPy! `w2` is a slice of `w`, but as in the cae of list, if you modify the copy you modify the original array.

In [131]:
w2 = w[:3, :3]
w2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Set this slice's values to zero ([:] selects the entire array)

In [132]:
w2[:] = 0
w2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [133]:
# w has been changed 
w

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

To avoid this problem, as with list, we use `copy` to create a copy that will not affect the original array.

In [136]:
w_copy = w.copy()
w_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [137]:
# Modifiying the copy
w_copy[:] = 10
print w_copy, '\n'
print w

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iterating Over Arrays

We can create a new 4 x 3 array of random numbers 0-9. We will use a NumPy method to get the random numbers: randint(low, high=None, size=None, dtype='l')

In [138]:
random_m = np.random.randint(0, 10, (4,3))

In [139]:
random_m

array([[2, 6, 0],
       [3, 3, 2],
       [9, 6, 0],
       [8, 5, 6]])

In [140]:
# Iterate by row
for row in random_m:
    print row

[2 6 0]
[3 3 2]
[9 6 0]
[8 5 6]


In [143]:
# Iterate by Index
for index in xrange(len(random_m)):
    print random_m[index]

[2 6 0]
[3 3 2]
[9 6 0]
[8 5 6]


In [145]:
# Iterate by row and index. We use enumerate() which is an iterator for index, value of iterable objects.
for index, row in enumerate(random_m):
    print 'row', row, 'index', index

row [2 6 0] index 0
row [3 3 2] index 1
row [9 6 0] index 2
row [8 5 6] index 3


In [150]:
for index, row in enumerate(random_m):
    print row, '+', index, '=', row + index

[2 6 0] + 0 = [2 6 0]
[3 3 2] + 1 = [4 4 3]
[9 6 0] + 2 = [11  8  2]
[8 5 6] + 3 = [11  8  9]


In [146]:
# Use zip to iterate over multiple iterables.
random_m_2 = random_m **2
random_m_2

array([[ 4, 36,  0],
       [ 9,  9,  4],
       [81, 36,  0],
       [64, 25, 36]])

In [148]:
for i, j in zip(random_m,random_m_2):
    print i, '+', j, '=', i + j

[2 6 0] + [ 4 36  0] = [ 6 42  0]
[3 3 2] + [9 9 4] = [12 12  6]
[9 6 0] + [81 36  0] = [90 42  0]
[8 5 6] + [64 25 36] = [72 30 42]


In [153]:
zip(random_m,random_m_2)

[(array([2, 6, 0]), array([ 4, 36,  0])),
 (array([3, 3, 2]), array([9, 9, 4])),
 (array([9, 6, 0]), array([81, 36,  0])),
 (array([8, 5, 6]), array([64, 25, 36]))]

In [163]:
# List coprenhencion
[i + j for i, j in zip(random_m,random_m_2)]

[array([ 6, 42,  0]),
 array([12, 12,  6]),
 array([90, 42,  0]),
 array([72, 30, 42])]